version: '3'
services:
  webapp:
    build: .
    container_name: "webapp"
    ports:
      - 3000:3000
    networks:
      - overlay
    links:
      - mysql_master
      - mysql_master2
      - mysql_slave
      - mysql_slave2
    depends_on:
      - mysql_master
      - mysql_master2
      - mysql_slave
      - mysql_slave2
  mysql_master:
    image: mysql:5.7
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    volumes:
      - ./master/data:/var/lib/mysql
    networks:
      - overlay

  mysql_slave:
    image: mysql:5.7
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    depends_on:
      - mysql_master
    volumes:
      - ./slave/data:/var/lib/mysql
    networks:
      - overlay

  mysql_master2:
    image: mysql:5.7
    env_file:
      - ./master2/mysql_master.env
    container_name: "mysql_master2"
    restart: "no"
    volumes:
      - ./master2/data:/var/lib/mysql
    networks:
      - overlay

  mysql_slave2:
      image: mysql:5.7
      env_file:
        - ./slave2/mysql_slave.env
      container_name: "mysql_slave2"
      restart: "no"
      depends_on:
        - mysql_master2
      volumes:
        - ./slave2/data:/var/lib/mysql
      networks:
        - overlay
networks:
  overlay: