
const ADD_ARTICLE = "ADD_ARTICLE"
const FOUND_BAD_WORD = "FOUND_BAD_WORD"
const FETCH_TWEETS = "FETCH_TWEETS" 
const DELETE_TWEET = "DELETE_TWEET"

export {ADD_ARTICLE, FOUND_BAD_WORD, FETCH_TWEETS, DELETE_TWEET}