
const ADD_ARTICLE = "ADD_ARTICLE"
const FETCH_TWEETS = "FETCH_TWEETS"
const DELETE_TWEET = "DELETE_TWEET"
const RE_TWEET = "RE_TWEET"
const TWEET_CREATED = "TWEET_CREATED"
const ARE_FETCHING = "ARE_FETCHING"

export {ADD_ARTICLE, FETCH_TWEETS, DELETE_TWEET, RE_TWEET, TWEET_CREATED, ARE_FETCHING}